### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tshemsedinov** [Vladyulik/Worderful#6]
1. It is not a good approach to use switch/case, use collection of functions instead: https://github.com/Vladyulik/Worderful/blob/d40585369a0f900bc8261d37d4c0662419c97d9f/client.js#L16-L34
2. Use const for result and you do not need predeclaration here, combine it with assignment: https://github.com/Vladyulik/Worderful/blob/d40585369a0f900bc8261d37d4c0662419c97d9f/networker.js#L35-L47
3. In mentioned above fragment you can save `this.queue[0]` to intermediate variable, below as well
4. Hardcoded magic numbers, like here https://github.com/Vladyulik/Worderful/blob/d40585369a0f900bc8261d37d4c0662419c97d9f/networker.js#L72 and https://github.com/Vladyulik/Worderful/blob/d40585369a0f900bc8261d37d4c0662419c97d9f/server.js#L64-L67 and https://github.com/Vladyulik/Worderful/blob/d40585369a0f900bc8261d37d4c0662419c97d9f/server.js#L110
5. Such an app state should not be global variables, it should be wrapped into abstraction like record/object, class, closure or monad: https://github.com/Vladyulik/Worderful/blob/d40585369a0f900bc8261d37d4c0662419c97d9f/server.js#L8-L16
6. Use collections instead of switch/case: https://github.com/Vladyulik/Worderful/blob/d40585369a0f900bc8261d37d4c0662419c97d9f/networker.js#L88-L95 and https://github.com/Vladyulik/Worderful/blob/d40585369a0f900bc8261d37d4c0662419c97d9f/client.js#L17-L33
7. No tests and CI (use Github actions for example)

But overall codestyle is consistent and looks fine

**Comment by Vladyulik** [comment]
Thanks for the code review! It was really detailed and helpful
